[package]
name = "strcuture"
version = "0.1.0"
edition = "2021"
authors = ["baeckg <doci1803@naver.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
